### ISSUE TITLE
icobench.ico.profile not workin

### ISSUE THREAD

**Issue by JoonasN** [zbone3/node-icobench#1]
Hey 

When I am trying to use "icobench.ico.profile({id: 678});" , i get error: 
"Parameter "ico" required, with a String value of id or url"..

maybe you can help?

**Comment by zbone3** [comment]
Hey

Sorry, my mistake in the documentation. 
IcoBench require a param named ico that can accept either ID or URL..
so instead of  `{id: 678}` please use `{ico: 678}`

As updated in the readme:
 ```js 
// Get more information on an ICO
icobench.ico.profile({ico: 678});
```
